#!/usr/bin/env python
#
# Yocto Build Server Stop Script
# Elizabeth Flanagan <elizabeth.flanagan@intel.com>
#
##
# Copyright (C) 2011-2012 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import os, sys, optparse, subprocess, signal, time
from socket import gethostname
from ConfigParser import SafeConfigParser

usage  = """%prog [options] controller|worker|both   

Stop a yocto buildbot autobuilder instance.
"""

parser = optparse.OptionParser(usage=usage)
options, args = parser.parse_args( sys.argv )

if len(args) != 2 or (sys.argv[1] != "both" and sys.argv[1] != "controller" and sys.argv[1] != "worker") :
    parser.error("""
    You must specify if you wish to stop controller, worker or both. 
   
    """ + usage )

AB_BASE=os.path.dirname(os.path.abspath(sys.argv[0]))

parser = SafeConfigParser()
parser.read('config/autobuilder.conf')
os.environ["WORKERBASEDIR"] = AB_BASE.strip('"') + "/yocto-worker"
print ' Setting %s to %s' % ("WORKERBASEDIR", AB_BASE + "/yocto-worker")
for section_name in parser.sections():
    for name, value in parser.items(section_name):
        os.environ[name.upper()] = value.strip('"').strip("'")

if sys.argv[1] == "controller" or sys.argv[1] == "both":
    os.chdir(os.path.join(AB_BASE, "yocto-controller"))
    subprocess.call(["make", "stop"])
    os.chdir(AB_BASE)

if sys.argv[1] == "worker" or sys.argv[1] == "both":
    if os.environ["PRSERV_HOST"] and os.environ["PRSERV_HOST"] == "localhost":
        os.chdir(AB_BASE)
        subprocess.call([os.path.join(AB_BASE, "ab-prserv"), "stop"])

    os.chdir(os.path.join(AB_BASE, "yocto-worker"))
    subprocess.call(["make", "stop"])
    os.chdir(AB_BASE)
    tmpfile = '/tmp/.buildworker-janitor'+os.getcwd().replace('/', '-')
    if os.path.exists(tmpfile) and os.path.isfile(tmpfile):
        print("A prior PID file exists. Attempting to kill.")
        with open(tmpfile, 'r') as f:
            pid=f.readline()
        try: 
            os.kill(int(pid), signal.SIGKILL)
            # We need to sleep for a second or two just to give the SIGKILL time
            time.sleep(2)
        except OSError as ex:
            print("""We weren't able to kill the prior buildworker-janitor. Trying again.""")
            pass
        # Check if the process that we killed is alive.
        try: 
           os.kill(int(pid), 0)
           raise Exception("""wasn't able to kill the process 
                              HINT:use signal.SIGKILL or signal.SIGABORT""")
        except OSError as ex:
           pass
    elif os.path.exists(tmpfile) and not os.path.isfile(tmpfile):
        raise Exception(tmpfile + """ is a directory. Remove it to continue.""")
    try:
        os.unlink(tmpfile)
    except:
        pass

